### ISSUE TITLE
Terminal font displays only solid black squares

### ISSUE THREAD

**Issue by neimanpinchas** [isotherm/betawise#2]
Wonderful, I think to use it as an alternative way to create fonts for the NEO2 without a mac

I've loaded the sample font, but i am getting black squares only (Character 0)

It seems to me that
            gd->pWidthTable = 0;
            gd->pOffsetTable = 0;
Should be pointers to some 1 dimensional array, containing incremental offsets to the beginning of each character.
We can see in the default fonts, that the neo is smart enough to use less space for a I, then a W (eM and eN)

**Comment by isotherm** [comment]
Those values are ok to be 0, since this is a monospaced font. This is a really rudimentary font converter, but perhaps we could support variable width fonts in the future.

There were a few bugs in the conversion script, which should be fixed in https://github.com/isotherm/betawise/commit/d1e1e79dd322a8fe170957d1198acbf74e149099. Unfortunately, if you've already installed the applet, Neo Manager won't update it without the version number changing.

For now, I changed the version to 0.0.S for you to try: [NeoFontTerminal.zip](https://github.com/isotherm/betawise/files/5093082/NeoFontTerminal.zip)

**Comment by neimanpinchas** [comment]
Works excellent

**Comment by isotherm** [comment]
Fixed in v0.06
